#################################################
# Binance
#################################################

binance.baseUrl=https://api.binance.com

#################################################
# Scanner
#################################################

scan.timeframes=ALL

#################################################
# Bollinger Band
#################################################

bb.length=50
bb.multiplier=0.2