#################################################
# Binance
#################################################

binance.futures.base-url=https://fapi.binance.com

#################################################
# Scanner
#################################################

scanner.timeframes=M15,H1,H4,D1,W1
scanner.candle.limit=200
scanner.ha.warmup=100

#################################################
# Bollinger Band
#################################################

bb.length=50
bb.multiplier=0.2

#################################################
# RSI
#################################################

transition.rsi.length=30

transition.rsi.oversold=30
transition.rsi.overbought=70

transition.rsi.touch.lookback=24

transition.rsi.timeframe=H1
transition.ha.timeframe=H4

#################################################
# General
#################################################

app.name=Confluence Scanner
app.version=1.0.0

scanner.download.threads=1

#################################################
# Bitunix
#################################################

bitunix.base-url=https://fapi.bitunix.com

#################################################
# Server
#################################################

server.port=${PORT:8080}
server.error.include-message=always
server.error.include-stacktrace=always
logging.level.root=INFO
logging.level.com.edison.scanner=DEBUG