#################################################
# Binance
#################################################

binance.futures.base-url=https://fapi.binance.com

#################################################
# Scanner
#################################################

scanner.timeframes=D1,H4,H1, M15
scanner.candle.limit=300
scanner.ha.warmup=500

#################################################
# Bollinger Band
#################################################

bb.length=50
bb.multiplier=0.2

#################################################
# General
#################################################

app.name=Confluence Scanner
app.version=1.0.0

scanner.download.threads=1

#################################################
# Bitunix
#################################################

bitunix.base-url=https://fapi.bitunix.com

#################################################
# Server
#################################################

server.port=${PORT:8080}